general {
    layout = dwindle

    allow_tearing = false

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}

dwindle {
    pseudotile = true
    preserve_split = true
    force_split = 2
    smart_resizing = true
}

master {
    new_status = master
}
