# ### Window rules ###
windowrule = opacity $windowOpacity override, match:fullscreen false

windowrule = opaque true, match:class kitty|foot|equibop|org\.quickshell|imv|swappy
windowrule = center true, match:float true, match:xwayland false

# Float
windowrule = float true, match:class yad
windowrule = float true, match:class zenity
windowrule = float true, match:class wev
windowrule = float true, match:class org\.gnome\.FileRoller
windowrule = float true, match:class file-roller
windowrule = float true, match:class blueman-manager
windowrule = float true, match:class feh
windowrule = float true, match:class imv
windowrule = float true, match:class system-config-printer
windowrule = float true, match:class org\.quickshell

# Float, resize and center
windowrule = float true, match:class org\.pulseaudio\.pavucontrol
windowrule = size 60% 70%, match:class org\.pulseaudio\.pavucontrol
windowrule = center 1, match:class org\.pulseaudio\.pavucontrol

# Special workspaces
windowrule = workspace special:sysmon, match:class btop
windowrule = workspace special:music, match:class feishin|Spotify|Supersonic|Cider|com.github.th_ch.youtube_music
windowrule = workspace special:music, match:initial_title Spotify( Free)?
windowrule = workspace special:communication, match:class discord|equibop|vesktop|whatsapp
windowrule = workspace special:todo, match:class Todoist

# Dialogs
windowrule = float true, match:title (Select|Open)( a)? (File|Folder)(s)?
windowrule = float true, match:title File (Operation|Upload)( Progress)?
windowrule = float true, match:title .* Properties
windowrule = float true, match:title Save As

# Picture in picture
windowrule = move 100%-w-2% 100%-w-3%, match:title Picture(-| )in(-| )[Pp]icture
windowrule = keep_aspect_ratio true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = float true, match:title Picture(-| )in(-| )[Pp]icture
windowrule = pin true, match:title Picture(-| )in(-| )[Pp]icture

# Creative software
windowrule = opaque true, match:class krita|gimp|inkscape|darktable|resolve|kdenlive|shotcut|blender|godot

# Steam
windowrule = rounding 10, match:class steam
windowrule = float true, match:title Friends List, match:class steam
windowrule = immediate true, match:class steam_app_[0-9]+
windowrule = idle_inhibit always, match:class steam_app_[0-9]+

# Floating terminal
windowrule = float true, match:class floatingterm

# ### Workspace rules ###
workspace = w[tv1]s[false], gapsout:$singleWindowGapsOut
workspace = f[1]s[false], gapsout:$singleWindowGapsOut

# ### Layer rules ###
layerrule = animation fade, match:namespace hyprpicker
layerrule = animation fade, match:namespace selection

# Fuzzel
layerrule = animation popin 80%, match:namespace launcher
layerrule = blur true, match:namespace launcher

# Caelestia shell
layerrule = no_anim true, match:namespace caelestia-(border-exclusion|area-picker)
layerrule = animation fade, match:namespace caelestia-(drawers|background)
layerrule = blur true, match:namespace caelestia-drawers
layerrule = ignore_alpha 0.57, match:namespace caelestia-drawers
