author = 'David Rodríguez (@daavidrgz)'
description = ''
credits = 'https://github.com/wujiocean/dotfiles'
dependencies = [
	'paperview-git',
	'bspwm',
	'sxhkd',
	'rofi',
	'polybar',
	'dunst',
	'pulseaudio',
	'feh',
	'brightnessctl',
	'playerctl',
	'mpd',
	'flameshot',
]
optional_dependencies = [
	'newsboat',
	'mpd-notification',
	'alacritty',
	'firefox',
	'better-discord',
	'spicetify',
	'neofetch',
	'zathura',
]
