author = 'David Rodríguez (@daavidrgz)'
description = 'desktop'
credits = 'http://github.com:daavidrgz'
dependencies = [
	'bspwm',
	'sxhkd',
	'picom',
	'rofi',
	'polybar',
	'dunst',
	'pulseaudio',
	'feh',
	'brightnessctl',
	'playerctl',
	'cava',
]
optional_dependencies = [
	'flameshot',
	'alacritty',
	'kitty',
	'firefox',
	'better-discord',
	'spicetify',
	'bottom',
	'neofetch',
]
