author = 'David Rodríguez (@daavidrgz)'
description = 'A desktop that brings you back to 90s, alongside all the features of modern software.'
credits = 'https://github.com/ChocolateBread799/dotfiles'
dependencies = [
	'awesome',
	'picom',
	'rofi',
	'pulseaudio',
	'feh',
	'brightnessctl',
	'playerctl'
	'flameshot',
	'firefox',
	'alacritty (Optional)',
	'better-discord (Optional)',
	'spicetify (Optional)',
	'bottom (Optional)',
]
