-- Shared settings for the caelestia desktop.
-- Colour scheme comes from scheme/current.lua (generated by the gtheme
-- `hyprland-scheme` pattern); values there are bare hex, no '#'.
local scheme = require("scheme.current")

local vars = {
    -- ### Apps ###
    terminal     = "kitty",
    fileExplorer = "thunar",

    -- ### Touchpad ###
    touchpadDisableTyping = true,
    touchpadScrollFactor  = 0.3,
    workspaceSwipeFingers = 4,
    gestureFingers        = 3,
    gestureFingersMore    = 4,

    -- ### Blur ###
    blurEnabled      = true,
    blurSpecialWs    = false,
    blurPopups       = true,
    blurInputMethods = true,
    blurSize         = 4,
    blurPasses       = 3,
    blurXray         = false,

    -- ### Shadow ###
    shadowEnabled     = true,
    shadowRange       = 4,
    shadowRenderPower = 3,
    shadowColour      = "rgba(1a1a1aee)",

    -- ### Gaps ###
    workspaceGaps       = 0,
    windowGapsIn        = 3,
    windowGapsOut       = 12,
    singleWindowGapsOut = 12,

    -- ### Window styling ###
    windowOpacity   = 1.0,
    windowRounding  = 10,
    windowBorderSize = 1,

    -- ### Cursor ###
    cursorTheme = "Bibata-Modern-Ice",
    cursorSize  = 24,
}

-- User overrides (create manually if needed: ~/.config/caelestia/hypr-vars.lua,
-- returning a table of the keys above).
local ok, user = pcall(dofile, os.getenv("HOME") .. "/.config/caelestia/hypr-vars.lua")
if ok and type(user) == "table" then
    for k, v in pairs(user) do vars[k] = v end
end

-- Derived after overrides so a user-supplied scheme/colour still applies.
vars.activeWindowBorderColour   = "rgba(" .. (scheme.secondary       or "7dcfff") .. "ff)"
vars.inactiveWindowBorderColour = "rgba(" .. (scheme.outlineVariant  or "414868") .. "ff)"
vars.scheme = scheme

return vars
