# ### Apps ###
$terminal = kitty
$fileExplorer = thunar

# ### Touchpad ###
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# ### Blur ###
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 4
$blurPasses = 3
$blurXray = false

# ### Shadow ###
$shadowEnabled = true
$shadowRange = 4
$shadowRenderPower = 3
$shadowColour = rgba(1a1a1aee)

# ### Gaps ###
$workspaceGaps = 0
$windowGapsIn = 3
$windowGapsOut = 12
$singleWindowGapsOut = 12

# ### Window styling ###
$windowOpacity = 1.0
$windowRounding = 10

$windowBorderSize = 1
$activeWindowBorderColour = rgba($secondaryff)
$inactiveWindowBorderColour = rgba($outlineVariantff)

# ### Cursor ###
$cursorTheme = Bibata-Modern-Ice
$cursorSize = 24
