author = 'David Rodríguez (@daavidrgz)'
description = 'A minimal dependency desktop using bspwm and polybar. It has square corners and double borders in windows.'
credits = 'https://github.com/mdnght-4/dotfiles'
dependencies = [
	'https://github.com/wmutils/opt (Tool to have double borders)',
	'bspwm',
	'sxhkd',
	'picom',
	'rofi',
	'polybar',
	'dunst',
	'pulseaudio',
	'feh',
	'brightnessctl',
	'playerctl',
	'flameshot',
	'alacritty (Optional)',
	'kitty (Optional)',
	'firefox (Optional)',
	'better-discord (Optional)',
	'spicetify (Optional)',
]
