author = 'David Rodríguez (@daavidrgz)'
description = 'Modern Hyprland desktop based on HyprKenso'
credits = 'https://github.com/aadritobasu/HyprKenso'
dependencies = [
	'hyprland',
	'waybar',
	'rofi-wayland',
	'swaync',
	'wlogout',
	'awww',
	'kitty',
	'brightnessctl',
	'playerctl',
	'swayosd',
	'hypridle',
	'hyprlock',
	'hyprpicker',
	'wl-clipboard',
	'cliphist',
	'polkit-gnome',
	'quickshell',
	'grim',
	'slurp',
	'satty',
]
optional_dependencies = [
	'fuzzel',
	'cava',
	'mpd',
	'mpd-mpris',
	'rmpc',
	'thunar',
	'brave',
	'alacritty',
	'firefox',
	'better-discord',
	'spicetify',
	'bottom',
	'neofetch',
]
