-- Hyprland config (Lua). Migrated from hyprland.conf (hyprlang) for Hyprland >= 0.55.
-- hyprlang is deprecated since 0.55 and will be dropped; see https://hypr.land/news/26_lua/
-- Docs: https://wiki.hypr.land/Configuring/
--
-- NOTE: hyprland.conf is kept next to this file purely as a rollback. Hyprland only
-- looks for hyprland.lua at STARTUP -- if it exists it wins and the .conf is ignored.
-- To roll back: mv hyprland.lua hyprland.lua.off  (then restart the session).

-- Theme colors, generated by the gtheme `hyprland-colors` pattern (post-script derives
-- colors/colors.lua from colors/colors.conf, which hyprlock still reads as hyprlang).
local colors = require("colors.colors")


------------------
---- MONITORS ----
------------------

-- Generated by the gtheme `hyprland-monitor` pattern.
require("monitors")


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "thunar"
local menu        = "rofi -show drun"


-------------------
---- AUTOSTART ----
-------------------

hl.on("hyprland.start", function()
    -- Activa la sesión gráfica de systemd (necesario para xdg-desktop-portal / screen share)
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE XDG_SESSION_TYPE && systemctl --user start hyprland-session.target")

    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("qs --path ~/.config/quickshell/hypr-overview")
    hl.exec_cmd("qs --path ~/.config/quickshell/hypr-lens")
    hl.exec_cmd("playerctld")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("qs --path ~/.config/quickshell/music")
    hl.exec_cmd("sattyd --daemon --copy-command wl-copy --early-exit --output-filename $HOME/pictures/screenshots/satty-%Y%m%d-%H%M%S.png")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- hyprlang could not expand $HOME/$PATH here, so the old `env = PATH,$HOME/.local/bin:$PATH`
-- line was a no-op. Lua expands it properly via os.getenv.
hl.env("PATH", os.getenv("HOME") .. "/.local/bin:" .. (os.getenv("PATH") or ""))
hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in     = 3,
        gaps_out    = 12,
        border_size = 1,

        col = {
            active_border   = colors.secondary,
            inactive_border = colors.outline_variant,
        },

        resize_on_border = false,
        allow_tearing    = false,

        layout = "dwindle",
    },

    decoration = {
        rounding = 10,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled  = true,
            size     = 4,
            passes   = 3,
            vibrancy = 0.5,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true,
        force_split    = 2,
    },

    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        mouse_move_enables_dpms  = true, -- wake the display from dpms off on mouse movement (e.g. after lock).
        key_press_enables_dpms   = true, -- wake the display from dpms off on key press (e.g. after lock).
    },
})

-- Animation curves (was `bezier = ...`)
hl.curve("smoothOut", { type = "bezier", points = { {0.36, 0},   {0.66, -0.56} } })
hl.curve("smoothIn",  { type = "bezier", points = { {0.25, 1},   {0.5, 1}      } })
hl.curve("overshot",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05}   } })
hl.curve("softSnap",  { type = "bezier", points = { {0.4, 0},    {0.2, 1}      } })
hl.curve("fluent",    { type = "bezier", points = { {0.0, 0.0},  {0.2, 1.0}    } })

hl.animation({ leaf = "windows",          enabled = true, speed = 5, bezier = "overshot", style = "popin 80%" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 5, bezier = "overshot", style = "popin 80%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 4, bezier = "smoothOut", style = "popin 95%" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 4, bezier = "softSnap" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 3, bezier = "smoothIn",  style = "slide" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 2, bezier = "softSnap",  style = "slide" })
hl.animation({ leaf = "fade",             enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 4, bezier = "smoothOut" })
hl.animation({ leaf = "fadeSwitch",       enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "fadeShadow",       enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "fadeDim",          enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "fadeDpms",         enabled = true, speed = 4, bezier = "smoothIn" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 5, bezier = "overshot", style = "slidefade 30%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5, bezier = "overshot", style = "slidefadevert 30%" })


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "altgr-intl",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        touchpad = {
            natural_scroll = true,
            scroll_factor  = 0.35,
        },

        repeat_rate  = 40,
        repeat_delay = 200,

        sensitivity = 0,
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

--------------------------
--   BASIC
--------------------------

-- Terminal emulator (opens in the last shell cwd, see _save_last_cwd in .zshrc)
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal .. [[ --directory "$(cat $HOME/.cache/last_cwd 2>/dev/null || echo $HOME)"]]))

-- Terminal emulator (nvidia gpu)
hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.exec_cmd("prime-run alacritty"))

-- Floating terminal
hl.bind(mainMod .. " + ALT + Return", hl.dsp.exec_cmd(terminal .. " --class floatingterm"))

-- Launcher
hl.bind(mainMod .. " + space", hl.dsp.exec_cmd(menu .. " || pkill rofi"))

-- Reload config
hl.bind(mainMod .. " + ALT + R", hl.dsp.exec_cmd("hyprctl reload"))

--------------------------
--   CUSTOM
--------------------------

hl.bind(mainMod .. " + CTRL + F", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + B",       hl.dsp.exec_cmd("brave"))
hl.bind(mainMod .. " + E",       hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",       hl.dsp.exec_cmd(terminal .. " nvim"))
hl.bind(mainMod .. " + Y",       hl.dsp.exec_cmd(terminal .. " --class floatingterm yazi"))
hl.bind(mainMod .. " + A",       hl.dsp.exec_cmd("swaync-client -t -sw"))
hl.bind(mainMod .. " + grave",   hl.dsp.exec_cmd("~/.config/rofi/scripts/key.sh"))
hl.bind(mainMod .. " + L",       hl.dsp.exec_cmd("loginctl lock-session"))

-- Archy — hold F12 to talk (add SUPER to attach a screenshot)
hl.bind("F12",          hl.dsp.exec_cmd("archy start"))
hl.bind("F12",          hl.dsp.exec_cmd("archy stop"),              { release = true })
hl.bind("SUPER + F12",  hl.dsp.exec_cmd("archy start --screenshot"))
hl.bind("SUPER + F12",  hl.dsp.exec_cmd("archy stop"),              { release = true })

--------------------------
--   HYPRLAND
--------------------------

-- Quit/Restart
hl.bind(mainMod .. " + ALT + Q", hl.dsp.exit())
-- Close/Kill window
hl.bind(mainMod .. " + W", hl.dsp.window.close())
-- Fullscreen
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }))

-- Window states
hl.bind(mainMod .. " + T",         hl.dsp.window.float())
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J",         hl.dsp.layout("togglesplit"))

--------------------------
--   FOCUS/SWAP
--------------------------

-- Focus direction
hl.bind(mainMod .. " + Left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + Down",  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + Up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + Right", hl.dsp.focus({ direction = "right" }))

-- Swap/move window direction
hl.bind(mainMod .. " + SHIFT + Left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + Down",  hl.dsp.window.move({ direction = "down" }))
hl.bind(mainMod .. " + SHIFT + Up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + Right", hl.dsp.window.move({ direction = "right" }))

-- Focus next window
hl.bind("ALT + Tab", hl.dsp.window.cycle_next())

-- Focus next/previous workspace
hl.bind(mainMod .. " + bracketleft",  hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. " + bracketright", hl.dsp.focus({ workspace = "m+1" }))

-- Move window to next/previous workspace
hl.bind(mainMod .. " + SHIFT + bracketleft",  hl.dsp.window.move({ workspace = "m-1" }))
hl.bind(mainMod .. " + SHIFT + bracketright", hl.dsp.window.move({ workspace = "m+1" }))

-- Focus next/previous monitor
hl.bind(mainMod .. " + ALT + bracketleft",  hl.dsp.focus({ monitor = "l" }))
hl.bind(mainMod .. " + ALT + bracketright", hl.dsp.focus({ monitor = "r" }))

-- Move window to next/previous monitor
hl.bind(mainMod .. " + ALT + SHIFT + bracketleft",  hl.dsp.window.move({ monitor = "l" }))
hl.bind(mainMod .. " + ALT + SHIFT + bracketright", hl.dsp.window.move({ monitor = "r" }))

-- Toggle overview (Mission Control)
hl.bind(mainMod .. " + Tab", hl.dsp.global("quickshell:overviewToggle"))

--------------------------
--   WORKSPACES
--------------------------

-- Focus workspace / move window to workspace / move silently
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
    hl.bind(mainMod .. " + CTRL + code:" .. (i + 9),
            hl.dsp.window.move({ workspace = i, follow = false }),
            { description = "move silently to workspace " .. i })
end

-- Scroll through workspaces
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + period",     hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + comma",      hl.dsp.focus({ workspace = "e-1" }))

--------------------------
--   MOVE/RESIZE
--------------------------

-- Move floating window
hl.bind(mainMod .. " + CTRL + Left",  hl.dsp.window.move({ x = -20, y = 0,  relative = true }))
hl.bind(mainMod .. " + CTRL + Down",  hl.dsp.window.move({ x = 0,   y = 20, relative = true }))
hl.bind(mainMod .. " + CTRL + Up",    hl.dsp.window.move({ x = 0,   y = -20, relative = true }))
hl.bind(mainMod .. " + CTRL + Right", hl.dsp.window.move({ x = 20,  y = 0,  relative = true }))

-- Resize window
hl.bind(mainMod .. " + ALT + Left",  hl.dsp.window.resize({ x = -20, y = 0,   relative = true }))
hl.bind(mainMod .. " + ALT + Down",  hl.dsp.window.resize({ x = 0,   y = 20,  relative = true }))
hl.bind(mainMod .. " + ALT + Up",    hl.dsp.window.resize({ x = 0,   y = -20, relative = true }))
hl.bind(mainMod .. " + ALT + Right", hl.dsp.window.resize({ x = 20,  y = 0,   relative = true }))

-- Move/resize with mouse
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

--------------------------
--   QUICKSHELL
--------------------------

-- Stash operations
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.global("quickshell:stashWorkspace"))
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.global("quickshell:unstashQuick"))

-- Screenshots/tools
hl.bind(mainMod .. " + SHIFT + A",       hl.dsp.global("quickshell:regionSearch"))
hl.bind(mainMod .. " + SHIFT + X",       hl.dsp.global("quickshell:regionOcr"))
hl.bind(mainMod .. " + SHIFT + R",       hl.dsp.global("quickshell:regionRecord"))
hl.bind(mainMod .. " + SHIFT + ALT + R", hl.dsp.global("quickshell:regionRecordWithSound"))

-- Color picker
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Music panel toggle
hl.bind(mainMod .. " + ALT + M", hl.dsp.exec_cmd("qs -c ~/.config/quickshell/music msg music toggle"))

--------------------------
--   WAYBAR/THEME
--------------------------

hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("~/.config/waybar/scripts/waybar-theme-rofi.sh"))
hl.bind(mainMod .. " + ALT + B",   hl.dsp.exec_cmd("~/.config/waybar/scripts/launch.sh"))
hl.bind(mainMod .. " + ALT + H",   hl.dsp.exec_cmd("~/.config/waybar/scripts/hide.sh"))
hl.bind(mainMod .. " + ALT + W",   hl.dsp.exec_cmd("~/.config/hypr/wppicker.sh"))
hl.bind(mainMod .. " + ALT + T",   hl.dsp.exec_cmd("~/.config/hypr/themepicker.sh"))
hl.bind(mainMod .. " + ALT + S",   hl.dsp.exec_cmd("~/.config/hypr/syslauncher.sh"))

-- Clipboard
hl.bind(mainMod .. " + ALT + C",  hl.dsp.exec_cmd("~/.config/hypr/clip.sh"))
hl.bind("CTRL + ALT + Delete",    hl.dsp.exec_cmd("cliphist wipe | pkill -USR1 rofi"))

-- Wlogout
hl.bind("ALT + Escape", hl.dsp.exec_cmd("~/.config/hypr/scripts/Wlogout.sh"))

--------------------------
--   SYSTEM
--------------------------

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"),       { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"),       { repeating = true, locked = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { repeating = true, locked = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"),  { repeating = true, locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("swayosd-client --brightness +10"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -10"), { repeating = true, locked = true })

-- Screenshots (fallback)
hl.bind("Print",          hl.dsp.exec_cmd([[geom=$(slurp) && sleep 0.15 && grim -t ppm -g "$geom" - | sattyd --filename -]]))
hl.bind("SUPER + Print",  hl.dsp.exec_cmd("grim -t ppm - | sattyd --filename -"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Ignore maximize requests from apps
hl.window_rule({
    name  = "windowrule-1",
    match = { class = ".*" },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name  = "windowrule-2",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({ name = "windowrule-3", match = { class = "^([Mm]pv|vlc)$" },                                                  tag = "+multimedia_video" })
hl.window_rule({ name = "windowrule-4", match = { class = "^(nm-applet|nm-connection-editor|blueman-manager|org.gnome.FileRoller)$" }, tag = "+settings" })
hl.window_rule({ name = "windowrule-5", match = { class = "^(org.gnome.DiskUtility|wihotspot(-gui)?)$" },                      tag = "+settings" })
hl.window_rule({ name = "windowrule-6", match = { class = "^(org.gnome.SystemMonitor)$" },                                     tag = "+viewer" })
hl.window_rule({ name = "windowrule-7", match = { class = "^(org.gnome.Evince)$" },                                            tag = "+viewer" })
hl.window_rule({ name = "windowrule-8", match = { class = "^(eog|org.gnome.Loupe)$" },                                         tag = "+viewer" })

hl.window_rule({
    name    = "windowrule-9",
    match   = { tag = "multimedia_video*" },
    no_blur = true,
    opacity = "1.0",
    float   = true,
    size    = {900, 506},
})

hl.window_rule({ name = "windowrule-10", match = { tag = "settings*" },                                          opacity = "0.8", float = true })
hl.window_rule({ name = "windowrule-11", match = { class = "^(org.gnome.Nautilus|code-insiders|thunar)$" },       opacity = "0.8" })
hl.window_rule({ name = "windowrule-12", match = { class = "^(gedit|org.gnome.TextEditor|geany)$" },              opacity = "0.8" })

hl.window_rule({
    name    = "windowrule-13",
    match   = { class = "^(org.pulseaudio.pavucontrol)$" },
    opacity = "0.8",
    float   = true,
    size    = {"monitor_w*0.5", "monitor_h*0.6"},
})

hl.window_rule({ name = "windowrule-14", match = { class = "^(kitty)$" },                  opacity = "0.9" })
hl.window_rule({ name = "windowrule-15", match = { class = "^(spotify)$" },                opacity = "0.8", workspace = "4 silent" })
hl.window_rule({ name = "windowrule-17", match = { class = "^(org.telegram.desktop)$" },   opacity = "0.8", workspace = "5 silent" })
hl.window_rule({ name = "windowrule-18", match = { class = "^(brave-browser)$" },          opacity = "0.8" })
hl.window_rule({ name = "windowrule-19", match = { class = "^(brave-browser)$", title = ".*YouTube.*" },  opacity = "1.0" })
hl.window_rule({ name = "windowrule-20", match = { class = "^(brave-browser)$", title = ".*HiAnime.*" },  opacity = "1.0" })
hl.window_rule({ name = "windowrule-21", match = { class = "^(brave-browser)$", title = ".*1Flix.*" },    opacity = "1.0" })

hl.window_rule({
    name         = "windowrule-22",
    match        = { class = "^(flameshot)$" },
    float        = true,
    center       = true,
    border_size  = 0,
    stay_focused = true,
})

-- Floating terminal
hl.window_rule({
    name    = "windowrule-23",
    match   = { class = "^(floatingterm)$" },
    float   = true,
    center  = true,
    size    = {"monitor_w*0.6", "monitor_h*0.6"},
    opacity = "0.8",
})

hl.window_rule({ name = "windowrule-24", match = { class = "^(code-insiders)$" }, workspace = "2" })
hl.window_rule({ name = "windowrule-25", match = { class = "^(geany)$" },         workspace = "2" })

hl.window_rule({
    name        = "windowrule-26",
    match       = { class = "^(music.py)$" },
    opacity     = "0.8",
    border_size = 0,
})

hl.window_rule({ name = "windowrule-27", match = { tag = "viewer*" }, float = true })

-- Pop-ups and dialogues
hl.window_rule({
    name   = "windowrule-28",
    match  = { title = "^(Save As|Save a File|Pick Files)$" },
    float  = true,
    size   = {"monitor_w*0.5", "monitor_h*0.6"},
    center = true,
})

hl.window_rule({ name = "windowrule-29", match = { initial_title = "(Open File)" }, float = true, size = {"monitor_w*0.7", "monitor_h*0.6"} })
hl.window_rule({ name = "windowrule-30", match = { initial_title = "(All Files)" }, float = true, size = {"monitor_w*0.7", "monitor_h*0.6"} })
hl.window_rule({ name = "windowrule-31", match = { class = "(hyprmixer)" },                 float = true, size = {"monitor_w*0.35", "monitor_h*0.45"} })
hl.window_rule({ name = "windowrule-32", match = { class = "(xdg-desktop-portal-gtk)" },    float = true, size = {"monitor_w*0.7", "monitor_h*0.6"} })
hl.window_rule({ name = "windowrule-33", match = { class = "(feh)" },                       float = true, size = {"monitor_w*0.7", "monitor_h*0.6"} })
hl.window_rule({ name = "windowrule-34", match = { class = "(com.gabm.satty)" },            float = true, size = {"monitor_w*0.7", "monitor_h*0.8"}, center = true })


-------------------
---- LAYER RULES --
-------------------

hl.layer_rule({ name = "layerrule-1", match = { namespace = "rofi" },          blur = true, ignore_alpha = 0.5, animation = "popin 60%" })
hl.layer_rule({ name = "layerrule-2", match = { namespace = "notifications" }, blur = true, ignore_alpha = 0 })
hl.layer_rule({ name = "layerrule-3", match = { namespace = "waybar" },        blur = true, ignore_alpha = 0.5 })
hl.layer_rule({ name = "layerrule-4", match = { namespace = "tag:notif*" },                 ignore_alpha = 0.5 })
hl.layer_rule({ name = "layerrule-5", match = { namespace = "logout_dialog" }, blur = true, animation = "slide top" })

-- Swaync blur & xray
hl.layer_rule({
    name         = "layerrule-6",
    match        = { namespace = "swaync-control-center" },
    blur         = true,
    ignore_alpha = 0.5,
    xray         = false,
    animation    = "slide right 60%",
})

hl.layer_rule({
    name         = "layerrule-7",
    match        = { namespace = "swaync-notification-window" },
    blur         = true,
    ignore_alpha = 0.5,
    xray         = false,
    animation    = "slide 60%",
})
