#! /bin/sh

# settings
bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

bspc config normal_border_color  "#1E1E2E"
bspc config active_border_color  "#1E1E2E"
bspc config focused_border_color "#1E1E2E"

setxkbmap -layout us -variant altgr-intl
xset r rate 200 40

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh
picom  &
~/.fehbg

pkill -f dborder-script &>/dev/null
pgrep -fi dborder-script || bash -c "exec -a dborder-script $HOME/.config/bspwm/dborder" &
