author = 'Rayhan Kafi Pratama (@rxyhn)'
description = 'A full animated desktop in awesomeWM, paired with pretty designed widgets.'
credits = 'https://github.com/rxyhn/dotfiles'
dependencies = [
	'awesome-git',
	'picom',
	'rofi',
	'alacritty',
	'brightnessctl',
	'pulseaudio',
	'playerctl',
	'mpd (Optional)',
	'mpc (Optional)',
	'mpdris2 (Optional',
	'ncmpcpp (Optional)',
]
