author = 'Rayhan Kafi Pratama (@rxyhn)'
description = 'A full animated desktop in awesomeWM, paired with pretty designed widgets.'
credits = 'https://github.com/rxyhn/dotfiles'
dependencies = [
	'awesome',
	'picom',
	'rofi',
	'brightnessctl',
	'pulseaudio',
	'playerctl',
]
optional_dependencies = [
	'kitty',
	'firefox',
	'mpd',
	'mpc',
	'mpdris2',
	'ncmpcpp',
]
