author = 'David Rodriguez (@daavidrgz)'
description = 'A simple and minimalistic desktop with rounded corners and subtle transparency.'
credits = 'https://github.com/joni22u/dotfiles'
dependencies = [
	'python-pulsectl',
	'bspwm',
	'sxhkd',
	'picom',
	'rofi',
	'dunst',
	'pulseaudio',
	'feh',
	'brightnessctl',
	'playerctl',
	'xob',
	'tint2',
	'flameshot',
]
optional_dependencies = [
	'alacritty',
	'kitty',
	'firefox',
	'better-discord',
	'spicetify',
	'neofetch',
	'bottom',
]
